package nerdfont

const (
	Animal      = ""
	Book        = ""
	Computers   = "󰌘"
	Directories = "󰙅"
	Docker      = "󰡨"
	Down        = "󰜮"
	Duplicate   = ""
	Emacs       = ""
	Git         = ""
	Github      = ""
	Globe       = ""
	Golang      = ""
	Graph       = ""
	Hourglass   = ""
	Java        = ""
	Lua         = ""
	Markdown    = ""
	Move        = "󰪹"
	Node        = ""
	Package     = "󰏗"
	Pencil      = ""
	Python      = ""
	Ruby        = ""
	Rust        = ""
	Search      = ""
	Shell       = ""
	Sync        = ""
	Text        = ""
	Tmux        = ""
	Trash       = ""
	Vi          = ""
	Warning     = ""
	Yc          = ""
	YouTube     = ""
)
