package stock

import (
	"despell/colors"
	"despell/core"
	"despell/icons"
)

func GetDefaults() map[string]core.Icon {
	return map[string]core.Icon{
		"Python":     {Icon: icons.Python, Color: colors.Yellow},
		"[tmux]":     {Icon: icons.Tmux, Color: colors.Green},
		"ack":        {Icon: icons.Search, Color: colors.Cyan},
		"atop":       {Icon: icons.Graph, Color: colors.Yellow},
		"bash":       {Icon: icons.Shell, Color: colors.Normal},
		"bat":        {Icon: icons.Animal, Color: colors.Magenta},
		"cat":        {Icon: icons.Animal, Color: colors.Red},
		"clx":        {Icon: icons.Yc, Color: colors.Orange},
		"curl":       {Icon: icons.Globe, Color: colors.Blue},
		"docker":     {Icon: icons.Docker, Color: colors.Blue},
		"duplicate":  {Icon: icons.Duplicate, Color: colors.Yellow},
		"exa":        {Icon: icons.Directories, Color: colors.Yellow},
		"fd":         {Icon: icons.Search, Color: colors.Cyan},
		"find":       {Icon: icons.Search, Color: colors.Cyan},
		"fish":       {Icon: icons.Shell, Color: colors.Normal},
		"fzf":        {Icon: icons.Search, Color: colors.Cyan},
		"gh":         {Icon: icons.Github, Color: colors.Blue},
		"git":        {Icon: icons.Git, Color: colors.Red},
		"glow":       {Icon: icons.Markdown, Color: colors.Magenta},
		"go":         {Icon: icons.Golang, Color: colors.Blue},
		"grep":       {Icon: icons.Search, Color: colors.Cyan},
		"htop":       {Icon: icons.Graph, Color: colors.Yellow},
		"http":       {Icon: icons.Globe, Color: colors.Blue},
		"java":       {Icon: icons.Java, Color: colors.Red},
		"lazygit":    {Icon: icons.Git, Color: colors.Red},
		"less":       {Icon: icons.Text, Color: colors.Magenta},
		"lf":         {Icon: icons.Directories, Color: colors.Yellow},
		"ls":         {Icon: icons.Directories, Color: colors.Yellow},
		"lua":        {Icon: icons.Lua, Color: colors.Blue},
		"lynx":       {Icon: icons.Globe, Color: colors.Blue},
		"man":        {Icon: icons.Book, Color: colors.Magenta},
		"more":       {Icon: icons.Text, Color: colors.Magenta},
		"mv":         {Icon: icons.Move, Color: colors.Yellow},
		"nano":       {Icon: icons.Pencil, Color: colors.Magenta},
		"nnn":        {Icon: icons.Directories, Color: colors.Yellow},
		"node":       {Icon: icons.Javascript, Color: colors.Yellow},
		"nvim":       {Icon: icons.Vim, Color: colors.Green},
		"pico":       {Icon: icons.Pencil, Color: colors.Magenta},
		"ping":       {Icon: icons.Globe, Color: colors.Blue},
		"ranger":     {Icon: icons.Directories, Color: colors.Yellow},
		"rg":         {Icon: icons.Search, Color: colors.Cyan},
		"rm":         {Icon: icons.Trash, Color: colors.Red},
		"rsync":      {Icon: icons.Sync, Color: colors.Red},
		"ruby":       {Icon: icons.Ruby, Color: colors.Red},
		"scp":        {Icon: icons.Computers, Color: colors.Cyan},
		"sleep":      {Icon: icons.Hourglass, Color: colors.Cyan},
		"ssh":        {Icon: icons.Computers, Color: colors.Cyan},
		"sudo":       {Icon: icons.Warning, Color: colors.Red},
		"tail":       {Icon: icons.Down, Color: colors.Cyan},
		"tig":        {Icon: icons.Git, Color: colors.Red},
		"tmux":       {Icon: icons.Tmux, Color: colors.Green},
		"top":        {Icon: icons.Graph, Color: colors.Yellow},
		"vi":         {Icon: icons.Vim, Color: colors.Green},
		"vim":        {Icon: icons.Vim, Color: colors.Green},
		"w3m":        {Icon: icons.Globe, Color: colors.Blue},
		"wget":       {Icon: icons.Globe, Color: colors.Blue},
		"youtube-dl": {Icon: icons.YouTube, Color: colors.Red},
		"zsh":        {Icon: icons.Shell, Color: colors.Normal},
	}
}
