package icons

const (
	Animal      = ""
	Book        = ""
	Computers   = ""
	Directories = "פּ"
	Docker      = ""
	Down        = ""
	Duplicate   = ""
	Git         = ""
	Github      = ""
	Globe       = ""
	Golang      = ""
	Graph       = ""
	Hourglass   = ""
	Java        = ""
	Javascript  = ""
	Lua         = ""
	Markdown    = ""
	Move        = ""
	Pencil      = "פֿ"
	Python      = ""
	Ruby        = ""
	Search      = ""
	Shell       = ""
	Sync        = ""
	Text        = ""
	Tmux        = "﬿"
	Trash       = "﫧"
	Vim         = ""
	Warning     = ""
	YouTube     = ""
	Yc          = ""
)
