package defaults

import (
	"github.com/bensadeh/despell/colors"
	"github.com/bensadeh/despell/core"
	"github.com/bensadeh/despell/nerdfont"
)

func GetDefaults() map[string]core.Icon {
	return map[string]core.Icon{
		"Python":     {Icon: nerdfont.Python, Color: colors.Yellow, Emoji: "🐍"},
		"[tmux]":     {Icon: nerdfont.Tmux, Color: colors.Green, Emoji: "🔩"},
		"ack":        {Icon: nerdfont.Search, Color: colors.Cyan, Emoji: "🔍"},
		"atop":       {Icon: nerdfont.Graph, Color: colors.Yellow, Emoji: "🔬"},
		"bash":       {Icon: nerdfont.Shell, Color: colors.Normal, Emoji: "🎩"},
		"bat":        {Icon: nerdfont.Animal, Color: colors.Magenta, Emoji: "🦇"},
		"cargo":      {Icon: nerdfont.Rust, Color: colors.Red, Emoji: "🦀"},
		"cat":        {Icon: nerdfont.Animal, Color: colors.Red, Emoji: "🐱"},
		"clx":        {Icon: nerdfont.Yc, Color: colors.Orange, Emoji: "🗞 "},
		"curl":       {Icon: nerdfont.Globe, Color: colors.Blue, Emoji: "🌎"},
		"docker":     {Icon: nerdfont.Docker, Color: colors.Blue, Emoji: "🐳"},
		"duplicate":  {Icon: nerdfont.Duplicate, Color: colors.Yellow, Emoji: "🍃"},
		"exa":        {Icon: nerdfont.Directories, Color: colors.Yellow, Emoji: "📁"},
		"fd":         {Icon: nerdfont.Search, Color: colors.Cyan, Emoji: "🔍"},
		"find":       {Icon: nerdfont.Search, Color: colors.Cyan, Emoji: "🔍"},
		"fish":       {Icon: nerdfont.Shell, Color: colors.Normal, Emoji: "🐠"},
		"fzf":        {Icon: nerdfont.Search, Color: colors.Cyan, Emoji: "🔍"},
		"gh":         {Icon: nerdfont.Github, Color: colors.Blue, Emoji: "🎋"},
		"git":        {Icon: nerdfont.Git, Color: colors.Red, Emoji: "🪵 "},
		"glow":       {Icon: nerdfont.Markdown, Color: colors.Magenta, Emoji: "🌟"},
		"go":         {Icon: nerdfont.Golang, Color: colors.Cyan, Emoji: "🐹"},
		"grep":       {Icon: nerdfont.Search, Color: colors.Cyan, Emoji: "🔦"},
		"htop":       {Icon: nerdfont.Graph, Color: colors.Yellow, Emoji: "🔬"},
		"http":       {Icon: nerdfont.Globe, Color: colors.Blue, Emoji: "🌎"},
		"java":       {Icon: nerdfont.Java, Color: colors.Red, Emoji: "☕️"},
		"lazygit":    {Icon: nerdfont.Git, Color: colors.Red, Emoji: "🎋"},
		"less":       {Icon: nerdfont.Text, Color: colors.Magenta, Emoji: "📕"},
		"lf":         {Icon: nerdfont.Directories, Color: colors.Yellow, Emoji: "📁"},
		"ls":         {Icon: nerdfont.Directories, Color: colors.Yellow, Emoji: "📁"},
		"lua":        {Icon: nerdfont.Lua, Color: colors.Blue, Emoji: "🌙"},
		"lynx":       {Icon: nerdfont.Globe, Color: colors.Blue, Emoji: "🌎"},
		"man":        {Icon: nerdfont.Book, Color: colors.Magenta, Emoji: "📘"},
		"more":       {Icon: nerdfont.Text, Color: colors.Magenta, Emoji: "📕"},
		"mv":         {Icon: nerdfont.Move, Color: colors.Yellow, Emoji: "🚚"},
		"nano":       {Icon: nerdfont.Pencil, Color: colors.Magenta, Emoji: "🖋"},
		"nnn":        {Icon: nerdfont.Directories, Color: colors.Yellow, Emoji: "📁"},
		"node":       {Icon: nerdfont.Javascript, Color: colors.Yellow, Emoji: "🌎"},
		"npm":        {Icon: nerdfont.Package, Color: colors.Red, Emoji: "📦"},
		"nvim":       {Icon: nerdfont.Vim, Color: colors.Green, Emoji: "🖋 "},
		"pico":       {Icon: nerdfont.Pencil, Color: colors.Magenta, Emoji: "🖋 "},
		"ping":       {Icon: nerdfont.Globe, Color: colors.Blue, Emoji: "🌎"},
		"ranger":     {Icon: nerdfont.Directories, Color: colors.Yellow, Emoji: "📁"},
		"rg":         {Icon: nerdfont.Search, Color: colors.Cyan, Emoji: "🔍"},
		"rm":         {Icon: nerdfont.Trash, Color: colors.Red, Emoji: "❌"},
		"rsync":      {Icon: nerdfont.Sync, Color: colors.Red, Emoji: "🔄"},
		"ruby":       {Icon: nerdfont.Ruby, Color: colors.Red, Emoji: "♦️"},
		"rustc":      {Icon: nerdfont.Rust, Color: colors.Red, Emoji: "🦀"},
		"safe-rm":    {Icon: nerdfont.Trash, Color: colors.Red, Emoji: "❌"},
		"scp":        {Icon: nerdfont.Computers, Color: colors.Cyan, Emoji: "🖥"},
		"sleep":      {Icon: nerdfont.Hourglass, Color: colors.Cyan, Emoji: "💤"},
		"spin":       {Icon: nerdfont.Down, Color: colors.Cyan, Emoji: "🌀"},
		"ssh":        {Icon: nerdfont.Computers, Color: colors.Cyan, Emoji: "🔑"},
		"sudo":       {Icon: nerdfont.Warning, Color: colors.Red, Emoji: "❗️"},
		"tail":       {Icon: nerdfont.Down, Color: colors.Cyan, Emoji: "🔽"},
		"tig":        {Icon: nerdfont.Git, Color: colors.Red, Emoji: "🎋"},
		"tmux":       {Icon: nerdfont.Tmux, Color: colors.Green, Emoji: "🔩"},
		"top":        {Icon: nerdfont.Graph, Color: colors.Yellow, Emoji: "🔬"},
		"vi":         {Icon: nerdfont.Vim, Color: colors.Green, Emoji: "🖋 "},
		"vim":        {Icon: nerdfont.Vim, Color: colors.Green, Emoji: "🖋 "},
		"w3m":        {Icon: nerdfont.Globe, Color: colors.Blue, Emoji: "🌎"},
		"wget":       {Icon: nerdfont.Globe, Color: colors.Blue, Emoji: "🌎"},
		"youtube-dl": {Icon: nerdfont.YouTube, Color: colors.Red, Emoji: "🎞"},
		"zsh":        {Icon: nerdfont.Shell, Color: colors.Normal, Emoji: "🎩"},
	}
}
