package emoji

const (
	AnticlockwiseArrows  = "🔄"
	Bat                  = "🦇"
	BookBlue             = "📘"
	BookRed              = "📕"
	Cat                  = "🐱"
	Coffee               = "☕️"
	Computer             = "🖥"
	Crab                 = "🦀"
	CrossMark            = "❌"
	DiamondsSuit         = "♦️"
	DownPointingTriangle = "🔽"
	FilmFrames           = "🎞"
	Folder               = "📁"
	Globe                = "🌎"
	HamsterFace          = "🐹"
	Key                  = "🔑"
	Leaves               = "🍃"
	MagnifyingGlass      = "🔍"
	Microscope           = "🔬"
	Moon                 = "🌙"
	MovingTruck          = "🚚"
	Newspaper            = "🗞 "
	NutAndBold           = "🔩"
	Package              = "📦"
	Pen                  = "🖋"
	RedExclamationMark   = "❗️"
	Snake                = "🐍"
	Spin                 = "🌀"
	Star                 = "⭐"
	TanabataTree         = "🎋"
	TopHat               = "🎩"
	TropicalFish         = "🐠"
	Whale                = "🐳"
	Wood                 = "🪵 "
	Zzz                  = "💤"
)
